In [1]:
pip install tensorflow

  Created wheel for termcolor: filename=termcolor-1.1.0-py3-none-any.whl size=4847 sha256=7aa924c43b93713a7988aa8c9ee36fe5d443087f58990a0c807480c54c6ba50f
  Stored in directory: c:\users\ezhlil mathi\appdata\local\pip\cache\wheels\b6\0d\90\0d1bbd99855f99cb2f6c2e5ff96f8023fad8ec367695f7d72d
Successfully built termcolor



In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras

import warnings
warnings.filterwarnings('ignore')

In [3]:
forest_data = pd.read_csv('forestfires.csv')
forest_data

month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain  ...  monthfeb  \
0     mar  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0  ...         0   
1     oct  tue  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0  ...         0   
2     oct  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0  ...         0   
3     mar  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2  ...         0   
4     mar  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0  ...         0   
..    ...  ...   ...    ...    ...   ...   ...  ..   ...   ...  ...       ...   
512   aug  sun  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0  ...         0   
513   aug  sun  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  ...         0   
514   aug  sun  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  ...         0   
515   aug  sat  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0  ...         0   
516   nov  tue  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0  ...         0   

     monthjan  monthjul  monthjun  monthmar  monthmay  monthnov  monthoct  \
0           0         0         0         1         0         0         0   
1           0         0         0         0         0         0         1   
2           0         0         0         0         0         0         1   
3           0         0         0         1         0         0         0   
4           0         0         0         1         0         0         0   
..        ...       ...       ...       ...       ...       ...       ...   
512         0         0         0         0         0         0         0   
513         0         0         0         0         0         0         0   
514         0         0         0         0         0         0         0   
515         0         0         0         0         0         0         0   
516         0         0         0         0         0         1         0   

     monthsep  size_category  
0           0          small  
1           0          small  
2           0          small  
3           0          small  
4           0          small  
..        ...            ...  
512         0          large  
513         0          large  
514         0          large  
515         0          small  
516         0          small  

[517 rows x 31 columns]

In [4]:
forest_data.shape

(517, 31)

In [5]:
forest_data.isna().sum()

month            0
day              0
FFMC             0
DMC              0
DC               0
ISI              0
temp             0
RH               0
wind             0
rain             0
area             0
dayfri           0
daymon           0
daysat           0
daysun           0
daythu           0
daytue           0
daywed           0
monthapr         0
monthaug         0
monthdec         0
monthfeb         0
monthjan         0
monthjul         0
monthjun         0
monthmar         0
monthmay         0
monthnov         0
monthoct         0
monthsep         0
size_category    0
dtype: int64

In [6]:
forest_data.dtypes

month             object
day               object
FFMC             float64
DMC              float64
DC               float64
ISI              float64
temp             float64
RH                 int64
wind             float64
rain             float64
area             float64
dayfri             int64
daymon             int64
daysat             int64
daysun             int64
daythu             int64
daytue             int64
daywed             int64
monthapr           int64
monthaug           int64
monthdec           int64
monthfeb           int64
monthjan           int64
monthjul           int64
monthjun           int64
monthmar           int64
monthmay           int64
monthnov           int64
monthoct           int64
monthsep           int64
size_category     object
dtype: object

### Data Preprocessing

In [7]:
forest_data.drop(labels='month',axis=1,inplace=True)
forest_data.drop(labels='day',axis=1,inplace=True)

In [8]:
x = forest_data.drop(labels='size_category',axis=1)
y = forest_data['size_category']

In [9]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [10]:
scaled_x = scaler.fit_transform(x)
scaled_x

array([[-8.05959472e-01, -1.32332557e+00, -1.83047676e+00, ...,
        -4.40225453e-02, -1.72859706e-01, -7.06081245e-01],
       [-8.10203395e-03, -1.17954077e+00,  4.88890915e-01, ...,
        -4.40225453e-02,  5.78503817e+00, -7.06081245e-01],
       [-8.10203395e-03, -1.04982188e+00,  5.60715454e-01, ...,
        -4.40225453e-02,  5.78503817e+00, -7.06081245e-01],
       ...,
       [-1.64008316e+00, -8.46647711e-01,  4.74768113e-01, ...,
        -4.40225453e-02, -1.72859706e-01, -7.06081245e-01],
       [ 6.80956663e-01,  5.49002541e-01,  2.69382214e-01, ...,
        -4.40225453e-02, -1.72859706e-01, -7.06081245e-01],
       [-2.02087875e+00, -1.68591332e+00, -1.78044169e+00, ...,
         2.27156334e+01, -1.72859706e-01, -7.06081245e-01]])

In [11]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [12]:
y_transform = le.fit_transform(y)

In [13]:
y_transform

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,

### Model Building

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(scaled_x,y_transform,test_size=0.20,random_state=12,stratify=y)

In [15]:
x_train.shape,y_train.shape,x_test.shape,y_test.shape

((413, 28), (413,), (104, 28), (104,))

In [16]:
y_test

array([1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1])

### Model Training

In [17]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Flatten,MaxPool2D

In [18]:
model = tf.keras.models.Sequential([tf.keras.layers.Flatten(input_dim = 28), #I/player
                                    tf.keras.layers.Dense(25,activation = 'relu'), #Hidden layer 1
                                    tf.keras.layers.Dense(1,activation = 'sigmoid')]) #O/p layer

In [19]:
model.compile(optimizer ='RMSprop',loss= 'binary_crossentropy',metrics =['accuracy'])

In [20]:
model.fit(x_train,y_train,epochs=30)

Epoch 1/30
13/13 [==============================] - 1s 5ms/step - loss: 0.7916 - accuracy: 0.4334
Epoch 2/30
13/13 [==============================] - 0s 8ms/step - loss: 0.7160 - accuracy: 0.5157
Epoch 3/30
13/13 [==============================] - 0s 6ms/step - loss: 0.6688 - accuracy: 0.6077
Epoch 4/30
13/13 [==============================] - 0s 6ms/step - loss: 0.6317 - accuracy: 0.6901
Epoch 5/30
13/13 [==============================] - 0s 6ms/step - loss: 0.6032 - accuracy: 0.7482
Epoch 6/30
13/13 [==============================] - 0s 6ms/step - loss: 0.5792 - accuracy: 0.7651
Epoch 7/30
13/13 [==============================] - 0s 5ms/step - loss: 0.5602 - accuracy: 0.7651
Epoch 8/30
13/13 [==============================] - 0s 5ms/step - loss: 0.5453 - accuracy: 0.7724
Epoch 9/30
13/13 [==============================] - 0s 6ms/step - loss: 0.5333 - accuracy: 0.7700
Epoch 10/30
13/13 [==============================] - 0s 4ms/step - loss: 0.5216 - accuracy: 0.7700
Epoch 11/30
13/13 [

In [21]:
model.evaluate(x_test,y_test)

4/4 [==============================] - 0s 4ms/step - loss: 0.6003 - accuracy: 0.7500


[0.6002616286277771, 0.75]

In [22]:
y_pred = model.predict(x_test)
y_pred

4/4 [==============================] - 0s 3ms/step


array([[0.8537563 ],
       [0.7737507 ],
       [0.8388751 ],
       [0.34102646],
       [0.6836945 ],
       [0.8403871 ],
       [0.662731  ],
       [0.7311863 ],
       [0.816946  ],
       [0.8523875 ],
       [0.7422097 ],
       [0.61418205],
       [0.44719484],
       [0.77354693],
       [0.862697  ],
       [0.73771447],
       [0.31249332],
       [0.62514335],
       [0.66313946],
       [0.84507996],
       [0.7744971 ],
       [0.7779612 ],
       [0.84393966],
       [0.8609741 ],
       [0.8930897 ],
       [0.81357944],
       [0.79936713],
       [0.5805962 ],
       [0.7476358 ],
       [0.7298104 ],
       [0.94829905],
       [0.734841  ],
       [0.75639045],
       [0.72484374],
       [0.26261705],
       [0.8256442 ],
       [0.7870135 ],
       [0.78620654],
       [0.99994296],
       [0.9857002 ],
       [0.7088549 ],
       [0.757791  ],
       [0.69536   ],
       [0.82246494],
       [0.5616554 ],
       [0.8552527 ],
       [0.84984094],
       [0.455

In [23]:
from sklearn.metrics import accuracy_score

In [24]:
pred=[]
for i in range(0,len(y_pred)):
    if y_pred[i]<0:
        y_pr=0
    else:
        y_pr=1
    pred.append(y_pr)

In [25]:
accuracy_score(y_test,pred)

0.7307692307692307